name: Update readme.txt and assets
on:
    push:
        branches: [trunk]
jobs:
    trunk:
        name: Push to trunk
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: mkdir -p .wordpress-org
            - name: WordPress.org plugin asset/readme update
              uses: 10up/action-wordpress-plugin-asset-update@2.1.1
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
