# This file is managed in https://github.com/happyprime/projects
name: Add new issues to Happy Prime project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/happyprime/projects/5
          github-token: ${{ secrets.AMIABOT_BOT_TOKEN }}
