# Run PHPUnit.
#
# This file is managed in https://github.com/happyprime/projects
name: PHPUnit

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  call-workflow:
    uses: happyprime/workflows/.github/workflows/phpunit.yml@trunk
