# Run WP.org's plugin check.
#
# This file is managed in https://github.com/happyprime/projects
name: WP.org Plugin Check

on:
  push:
    branches:
      - trunk
    # A change to another workflow file is no reason to run this one.
    paths:
      - '**'
      - '!.github/workflows/**'
      - .github/workflows/plugin-check.yml
  pull_request:
    branches:
      - trunk
    # A change to another workflow file is no reason to run this one.
    paths:
      - '**'
      - '!.github/workflows/**'
      - .github/workflows/plugin-check.yml

jobs:
  call-workflow:
    uses: happyprime/workflows/.github/workflows/plugin-check.yml@trunk
    with:
      php-version: '8.3'
